### ISSUE TITLE
Crash while pressing F3

### ISSUE THREAD

**Issue by Spinoyonyx** [superlord9362/Prehistoric-Fauna#12]
In the cretaceous dimension i pressed F3 and crashed
[crash-2021-06-05_15.29.33-client.txt](https://github.com/superlord9362/Prehistoric-Fauna/files/6602179/crash-2021-06-05_15.29.33-client.txt)

**Comment by Shunosaurus** [comment]
Had the same problem, also happened in the triassic and jurassic. Only happened the first time I pressed f3 in the dimension though.

**Comment by superlord9362** [comment]
It seems to be an access transformer issue, we'll see what we can do.
