### ISSUE TITLE
Game keeps freezing when i try to neter and leave the cretacous, (maybe the other dimesions too)

### ISSUE THREAD

**Issue by crydigo** [superlord9362/Prehistoric-Fauna#17]
when I entered the cretaceous I took of everything to see and test. but when I entered I was frozen and had weird visuals like may arm looked weird, I could break leaves but it wouldn't drop anything. I waited and I wasn't frozen so I tested and look at my fps which was normal, after that i left to go back through the portal but then it froze again but looked worse then before, I yet again could break stuff but nothing would drop, i waited for a very long time but nothing happened so I used a /home feature I added as i could still type, after a bit the /home feature worked but when i reached home it was really leggy and I had 1 to 2 FPS so i reloaded the chunks. never worked, i left and re-joined the world but still never worked, i tried this a couple times before leaving Minecraft and re-joining, it worked so i went back into the cretaceous but then it happened again, i was frozen in the cretaceous and it had weird visuals again, so then i reloaded chunks which completely crashed the game, i went back into teh game but it wasnt working and kept crashing and said this error messasage

The game crashed whilst initializing game
Error: java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
Exit Code: -1

after waiting for a while it finally worked but these problems are still a problem

btw here's my mod list if you think that its something to do with my mods which are affecting  

![2021-06-05 (2)](https://user-images.githubusercontent.com/85441046/120924323-09341100-c6cb-11eb-9810-34620984bb0a.png)

**Comment by superlord9362** [comment]
Can you supply a crash log?

**Comment by crydigo** [comment]
it started working again so i cant get one but its still concerning that this happens. its mainly entering and leaving the dimension in survival which is a problem

**Comment by superlord9362** [comment]
The small lag where nothing happens is a MC thing, and isn't really fixable by us. It's the world finishing loading.
