### ISSUE TITLE
Journal dont work after using pages on it

### ISSUE THREAD

**Issue by JoojiDraws** [superlord9362/Prehistoric-Fauna#21]
The journal opens normally when i use the one without any information and only the introduction, but after adding anything the game freezes if i dont press "esc"

And also, the pages on the book thing duplicates
they disapear when i close the block but when i open it again they reaper and i can putt more stuff into the journal

[tlauncher_06_09_2021_02_27_39.log](https://github.com/superlord9362/Prehistoric-Fauna/files/6622250/tlauncher_06_09_2021_02_27_39.log)

**Comment by superlord9362** [comment]
Could you follow these steps, as it will make it a lot easier for me to identify the problem:
Close any instances of Minecraft running.
Open a new instance
Create a new creative world
Open the Ancient Journal
Send the file named latest.log
