### ISSUE TITLE
im trying to open the game and it crashes

### ISSUE THREAD

**Issue by crydigo** [superlord9362/Prehistoric-Fauna#22]
this is the crash log

Error: java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
Exit Code: -1

its now working but this just needs a fix

**Comment by superlord9362** [comment]
That isn't a crash log. You can find crash reports at C:\Users\(User)\AppData\Roaming\.minecraft\crash-reports
