### ISSUE TITLE
Journal issue

### ISSUE THREAD

**Issue by JoojiDraws** [superlord9362/Prehistoric-Fauna#23]
I hope this logs works now

But the general bug is

when i open the journal by the first time it works fine, but the images dont appear, and when i open it again the freeze thing happens
[latest.log](https://github.com/superlord9362/Prehistoric-Fauna/files/6627417/latest.log)

**Comment by superlord9362** [comment]
No errors are being recorded by the log. May be an optifine issue? I can see where you put it in your inventory, but nothing is saying that there was an issue loading anything.
