### ISSUE TITLE
Crash as soon as the title screen loads

### ISSUE THREAD

**Issue by Bruh2801** [superlord9362/Prehistoric-Fauna#24]
i dont think i even get a crash report in the crash report folder though i got this
idk why
![Minecraft Launcher 11 06 2021 14_46_20](https://user-images.githubusercontent.com/85746018/121689457-e89df980-cac4-11eb-833c-e04e1e4831fb.png)

**Comment by superlord9362** [comment]
We can't work with this A crash report from the folder is needed, as this doesn't give any information on what caused it.

**Comment by Bruh2801** [comment]
> We can't work with this A crash report from the folder is needed, as this doesn't give any information on what caused it.

sadly it just doesnt want to give me the crash report so imma just close this instead
