### ISSUE TITLE
Extremely cool mod just what 1.16.5 needs, minor feedback

### ISSUE THREAD

**Issue by Mr-Syntax** [superlord9362/Prehistoric-Fauna#32]
Could you add a config option to merge all the timeperiods into one portal?
my pack isent really scientifically accurate anyway.... :D 
another thing, if you could add a config to just add the biomes into the world generation and allow all the mobs to spawn in the overworld at the same time that would be extremely cool
this would also make it very flexible to make it suit basically any need.
im putting the mod in this pack as we speak
https://www.curseforge.com/minecraft/modpacks/chosencraft

it would look so damn cool if you could make it compatible with immersive portals
and + if you could have a config for the portal being uncraftable but it generates at the time temple intact just waiting to be lit that could also be pretty cool :)

**Comment by superlord9362** [comment]
We have the Prehistoric World Type, which changes the world to be all the prehistoric biomes. That's the most we're really planning on doing with prehistoric stuff being in the overworld/mushed together at the moment.

**Comment by Mr-Syntax** [comment]
ahh okay fair, could you perhaps be talked into doing the merged dimension of all the eras?

**Comment by superlord9362** [comment]
That would require a lot more than just a config option, as it would require removing the other dimensions on toggled, changing how the time totems work, and a lot of world gen toggling.

**Comment by Mr-Syntax** [comment]
fair enough, just thought id mention it i know its alot of work and thank you for doing the mod, had been looking for a dinosaur dimension mod for 1.16.5 for a long time

**Comment by superlord9362** [comment]
Thanks for enjoying it!
