### ISSUE TITLE
Wall Fossils and Ancient paintings pop off walls (1.16)

### ISSUE THREAD

**Issue by Temosaurus** [superlord9362/Prehistoric-Fauna#33]
To elaborate further, I set up all of the wall fossils and ancient paintings on a wall, and then left to go do something else. When I returned and the chunk loaded, I noticed that all of the paintings were now facing the opposite direction, and since there was nothing that they were attached to, they all popped off. Specifically they were facing North when I placed them, and were facing south when the chunk reloaded. They will also face south if placed facing east or west, but act fine if facing south.

**Comment by superlord9362** [comment]
Fixed for 2.1.2
