### ISSUE TITLE
When you put a stair or a wall on a spike trap it looses its texture

### ISSUE THREAD

**Issue by crydigo** [superlord9362/Prehistoric-Fauna#34]

**Comment by HugoMage** [comment]
seems like a problem with the json model not supporting the position of the spike trap

**Comment by superlord9362** [comment]
Is this for version 2.1.1? Unable to replicate the bug.

**Comment by superlord9362** [comment]
Closing due to inability to replicate the issue. Feel free to re-open if issue persists in 2.1.3.
