### ISSUE TITLE
Crash twilight forest dimension

### ISSUE THREAD

**Issue by DiegoGroza** [superlord9362/Prehistoric-Fauna#35]

**Comment by superlord9362** [comment]
I will need your crash report, as well as more information on what was happening when the game crashed.

**Comment by DiegoGroza** [comment]
Minecraft crashes while twilight forest is loading after entering portal. Sometimes It doesn't crash, but after I walk a little bit in the twilight forest it crashes.
[crash-2021-10-26_17.34.33-server.txt](https://github.com/superlord9362/Prehistoric-Fauna/files/7419047/crash-2021-10-26_17.34.33-server.txt)

**Comment by zOnlyKroks** [comment]
Probably from skincape mod. There is no mention of this mod there.

**Comment by DiegoGroza** [comment]
That mod didn't cause crashes.. Here I tried to do the same thing without  TLSkinCape. This time the game didn't crash while I was loading into twilight forest (often it crashes at this stage). I spend 2 minutes flying in one direction and minecraft crashed. 
I tried to run the game with just twilight forest mod, and everything was ok. The game crashes only when I add  Prehistoric Fauna.
[crash-2021-10-30_16.40.33-server.txt](https://github.com/superlord9362/Prehistoric-Fauna/files/7446679/crash-2021-10-30_16.40.33-server.txt)

**Comment by Mermelad4** [comment]
I have the same problem, only with those two mods together it happens to me.

**Comment by Spudstak** [comment]
Having the same issue here. Here's my crashlog, looks like it is different than the OP's it mentions spawning your structures the twilight. Which could explain why it happens after loading a few chunks and not right away every time.
[crash-2021-11-03_20.01.23-server.txt](https://github.com/superlord9362/Prehistoric-Fauna/files/7471220/crash-2021-11-03_20.01.23-server.txt)

**Comment by superlord9362** [comment]
Fixed for 2.1.2
