### ISSUE TITLE
Had this crash a couple of times with the new terraforged beta

### ISSUE THREAD

**Issue by Mr-Syntax** [superlord9362/Prehistoric-Fauna#37]
its not everytime it happens so i dont know whats the cause
[crash-2021-11-18_00.26.24-client.txt](https://github.com/superlord9362/Prehistoric-Fauna/files/7558622/crash-2021-11-18_00.26.24-client.txt)

**Comment by superlord9362** [comment]
Should be fixed for 2.1.2
