### ISSUE TITLE
Can't create any world. Problem with Quark.

### ISSUE THREAD

**Issue by DiegoGroza** [superlord9362/Prehistoric-Fauna#40]
![Screenshot_1](https://user-images.githubusercontent.com/93182571/147469318-94fb29d2-7f27-44f5-8588-c464b62abe37.png)

**Comment by DiegoGroza** [comment]
I can't create any world. A conflict occurs between prehistoric fauna and quark(only when I use both of them)
Even if I click safe mode nothing happens. It works ok with previous version of prehistoric fauna.

**Comment by superlord9362** [comment]
Please send your latest.log

**Comment by DiegoGroza** [comment]
[latest.log](https://github.com/superlord9362/Prehistoric-Fauna/files/7780514/latest.log)

**Comment by IvorAmlug** [comment]
Than that might be the thing crashin my server too

**Comment by superlord9362** [comment]
Fixed for 2.1.3
