### ISSUE TITLE
Fossils spawning in other dimensions

### ISSUE THREAD

**Issue by fatzle** [superlord9362/Prehistoric-Fauna#45]
this issue has been apparent for a while, but fossils seem to spawn in the nether and end biomes for me, not just modded biomes but vanilla biomes. They also spawn in the Undergarden to.

**Comment by fatzle** [comment]
another dimension mod i tested it with was Blue Skies but they were fine nothing out of the ordinary

**Comment by superlord9362** [comment]
Unable to recreate this. What version of the mod are you using?

**Comment by fatzle** [comment]
> Unable to recreate this. What version of the mod are you using?

version 2.1.3 for 1.16.5

**Comment by fatzle** [comment]
very sorry for late response

**Comment by fatzle** [comment]
i think it has to do with byg and the undergarden thats why they spawned i tested with out them and it worked just fine

**Comment by superlord9362** [comment]
Fixed for 2.2.0
