### ISSUE TITLE
Time Temples spawn in other mods' dimension

### ISSUE THREAD

**Issue by ghost** [superlord9362/Prehistoric-Fauna#46]
Other mods: like [atum](https://www.curseforge.com/minecraft/mc-mods/atum)
Atum has a world generation similar to the overworld desert, so it's understandable that time temples just generate in it.
It would be nice if you provide a dimension whitelist about time temples generation in the config.

**Comment by Dasawkem** [comment]
Seconded, these structures spawn in every non vanilla dimension for me. Would be good to get a dimensional blacklist and/or whitelist, perhaps even a biome blacklist and/or whitelist.

**Comment by JosephPro2004** [comment]
Similarly, I've been getting the fossils in dimensions they shouldn't be in (in this case, [Dalek Mod](https://www.curseforge.com/minecraft/mc-mods/the-dalek-mod).) Even though the creator himself said [it was fixed](https://github.com/superlord9362/Prehistoric-Fauna/issues/45#issuecomment-1255696979), it wasn't-

![2023-05-06_16 33 15](https://user-images.githubusercontent.com/132520389/236650548-92f84cb5-5215-4ecb-9fc7-b2f6a49fad94.png)
![2023-05-06_16 34 20](https://user-images.githubusercontent.com/132520389/236650563-1d3e6054-7bc4-41a4-b194-3e515d5bcb3b.png)
![2023-05-06_16 35 17](https://user-images.githubusercontent.com/132520389/236650567-c144d737-face-4624-b9ac-66b7eb8fc0a9.png)

I'm entirely on board with the dimension/biome blacklist/whitelist idea.

**Comment by superlord9362** [comment]
Fixed in 2.3.0. Now uses biome tags, so will be more customizeable.
