### ISSUE TITLE
crash to do with PHF, unsure what is causing it

### ISSUE THREAD

**Issue by wizardwyit** [superlord9362/Prehistoric-Fauna#47]
[crash-2022-07-21_14.11.33-server.txt](https://github.com/superlord9362/Prehistoric-Fauna/files/9162852/crash-2022-07-21_14.11.33-server.txt)

**Comment by superlord9362** [comment]
What are you doing when it crashes?

**Comment by wizardwyit** [comment]
I’m literally just walking around in a cave and then it happens

**Comment by superlord9362** [comment]
I believe this has been fixed for next update. If issue continues after 2.2.0's release, feel free to re-open.
