### ISSUE TITLE
Minecraft will crash when placing the Paleontology Table.

### ISSUE THREAD

**Issue by iistiR** [superlord9362/Prehistoric-Fauna#49]
[crash-2022-09-10_18.31.07-server.txt](https://github.com/superlord9362/Prehistoric-Fauna/files/9540885/crash-2022-09-10_18.31.07-server.txt)

**Comment by superlord9362** [comment]
I believe this has been fixed for next update. If issue continues after 2.2.0's release, feel free to re-open.
