### ISSUE TITLE
Signs do not render Caves & Cliffs Backport's glow ink. 

### ISSUE THREAD

**Issue by GodzillaFan13** [superlord9362/Prehistoric-Fauna#51]
another similarly self-explanatory sign issue, when playing with Caves & Cliffs Backport (https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs-backport), using glow ink on any Prehistoric Fauna sign, the text does not change. 
![Screenshot (38)](https://user-images.githubusercontent.com/112220126/191325959-8e4fd982-4c1b-418b-b9f0-1f083ff751e3.png)

**Comment by superlord9362** [comment]
No longer an issue for supported versions
