### ISSUE TITLE
World Gen Crash

### ISSUE THREAD

**Issue by mxnmnm** [superlord9362/Prehistoric-Fauna#54]
https://gist.github.com/mxnmnm/aeecd7f8ea3f608209f859d0fb790904

**Comment by superlord9362** [comment]
Does this still occur in 2.2.5?

**Comment by mxnmnm** [comment]
no clue it has been a while since I've used 1.16.5

**Comment by superlord9362** [comment]
Very fair. Will close for now, as 2.3.0 will be for 1.18/19/20
