### ISSUE TITLE
TerraForged Problem

### ISSUE THREAD

**Issue by Kasualix** [superlord9362/Prehistoric-Fauna#56]
TerraForged + Prehistoric Fauna cause the biomes in prehistoric dimensions generate in overworld.
![image](https://user-images.githubusercontent.com/110756250/214043246-5b9020dc-d22a-4efe-b3fe-7130c0b2fcbf.png)

**Comment by superlord9362** [comment]
Petrified Forest is an overworld biome that Prehistoric Fauna adds.
