### ISSUE TITLE
BUG FISHING WITH AQUACULTURE 2

### ISSUE THREAD

**Issue by brahemchb** [superlord9362/Prehistoric-Fauna#58]
I can't catch the fish from the Aquaculture 2 mod, I've been fishing for hours and nothing came out. I looked for why they didn't come out, and the only mod that gave me a conflict between them is Aquaculture 2 and Prehistoric Fauna. I have these versions of each mod:

- Aquaculture-1.16.5-2.1.23.jar
- Prehistoric Fauna 2.1.3.jar

I'm in love with this mod, please don't leave it and try to improve it so that the whole minecraft community loves your creation.

**Comment by Kasualix** [comment]
duplicate https://github.com/superlord9362/Prehistoric-Fauna/issues/38

**Comment by superlord9362** [comment]
> duplicate #38
