### ISSUE TITLE
[Suggestion] Progression system

### ISSUE THREAD

**Issue by delveticas** [superlord9362/Prehistoric-Fauna#64]
the mod has some absolutely gorgeous design and visuals, however i believe its really lacking one certain thing — an incentive. a clear incentive for prayer to go and play through all of the stages of the mod. 

and i have came up with an idea, a progression system. here's what i have in mind: the player starts the game already in the first era and has to survive and make his way to find and fix the broken portal into the second era, and then to the third. only after completing the third era the player is allowed to get in the overworld.

what do you think? let me know, i think it sounds fun asf delveticas@gmail.com

**Comment by superlord9362** [comment]
We have thought about adding a "Broken Portal" config option which traps the player in the past. It wouldn't work like you wrote, but may be something in the future.
