### ISSUE TITLE
Unable to load in new worlds

### ISSUE THREAD

**Issue by Subthy** [superlord9362/Prehistoric-Fauna#65]
Hello there,

I have a little of a problem with the mod. Usually, I can load into the first world fine (sometimes not), but I am unable to create a second world during the same session. It becomes stuck at 100%. Not really sure where to look in the log about this one.
[debug (2).log](https://github.com/superlord9362/Prehistoric-Fauna/files/12704611/debug.2.log)
[latest.log](https://github.com/superlord9362/Prehistoric-Fauna/files/12704612/latest.log)

**Comment by superlord9362** [comment]
Is the issue still occuring?

**Comment by Subthy** [comment]
Yes, the issue is still there. Would you like a newer latest.log and debug.log? I can even provide a thread dump, if needed.

**Comment by NightingaleZK** [comment]
I had this issue before I added Prehistoric Fauna to my modpack list, and the issue still persists. I'm just saying this because the fault may not be with the Prehistoric Fauna mod.

**Comment by superlord9362** [comment]
If PF related, next update should fix this
