### ISSUE TITLE
Velociraptors suffocate in small spaces they can pathfind into

### ISSUE THREAD

**Issue by LordDaxius** [superlord9362/Prehistoric-Fauna#67]
![image_2023-12-04_151611648](https://github.com/superlord9362/Prehistoric-Fauna/assets/49254167/c9431072-8814-4b82-9632-e506d3fb7753)
![image_2023-12-04_151656949](https://github.com/superlord9362/Prehistoric-Fauna/assets/49254167/a07eaf61-a02b-4ce6-960f-7119fd4939e9)

Unsure on specific reproduction steps. These were tamed velociraptors, on version 1.16.5. Happened in both wandering and following mode. I have circled the areas where they suffocated and I found their drops, hope it helps.

**Comment by LordDaxius** [comment]
Mod version is 2.2.5, forgot to mention that

**Comment by superlord9362** [comment]
Fixed for 2.3.0
