### ISSUE TITLE
Allosaurus hunting AI is buggy

### ISSUE THREAD

**Issue by Beam196** [superlord9362/Prehistoric-Fauna#73]
Take a look in the video

https://github.com/superlord9362/Prehistoric-Fauna/assets/83494572/54eea1d2-289f-4155-bb71-cca08c765835

Explaination: Even with preys in the front when the allosaurus is hungry they will still randomly move not chasing preys

**Comment by Beam196** [comment]
Uploading XiaoYing_Video_1720625526698.mp4…

**Comment by superlord9362** [comment]
They may not be actively hunting. If they are, issue is fixed for next update or at least, unrecreatable
